---

version:  1.4.0
dependencies: []

galaxy_info:
  author: Sergei Antipov
  company: 2GIS
  description: Manage MongoDB with authentication and replica sets
  license: GPLv2
  min_ansible_version: 1.8
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - database
  - database:nosql
