---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [mongodb]

- include: configure.yml
  tags: [mongodb]

- include: replication_init_auth.yml
  when: ( mongodb_conf_replSet is defined and mongodb_conf_auth
        and mongodb_master is defined and mongodb_master )
  tags: [mongodb]

- include: replication.yml
  when: mongodb_conf_replSet is defined
  tags: [mongodb]

- include: auth_initialization.yml
  when: mongodb_conf_auth and not mongodb_conf_replSet
  tags: [mongodb]

- include: mms-agent.yml
  when: mongodb_mms_api_key != ""
  tags: [mongodb]
